# Generated by Django 4.1.1 on 2022-09-13 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatteryCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cell_name_id", models.CharField(max_length=255)),
                ("cycles", models.FloatField(default=0, max_length=255)),
                ("capacity_ah", models.FloatField(default=0, max_length=255)),
                (
                    "cathode",
                    models.CharField(
                        choices=[
                            ("LCO", "Lco"),
                            ("LFP", "Lfp"),
                            ("NCA", "Nca"),
                            ("NMC", "Nmc"),
                            ("NMC-LCO", "Nmc Lco"),
                        ],
                        default="LCO",
                        max_length=7,
                    ),
                ),
                (
                    "anode",
                    models.CharField(
                        choices=[("graphite", "Graphite")],
                        default="graphite",
                        max_length=8,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("18650", "Type 18650"),
                            ("pouch", "Pouch"),
                            ("prismatic", "Prismatic"),
                        ],
                        default="18650",
                        max_length=9,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("HNEI", "Hnei"),
                            ("UL-PUR", "Ul Pur"),
                            ("calce", "Calce"),
                            ("oxford", "Oxford"),
                            ("snl", "Snl"),
                        ],
                        default="HNEI",
                        max_length=6,
                    ),
                ),
                ("temperature_c", models.FloatField(default=0, max_length=255)),
                ("max_state_of_charge", models.FloatField(default=0, max_length=255)),
                ("min_state_of_charge", models.FloatField(default=0, max_length=255)),
                ("depth_of_discharge", models.FloatField(default=0, max_length=255)),
                ("charge_capacity_rate", models.FloatField(default=0, max_length=255)),
                (
                    "discharge_capacity_rate",
                    models.FloatField(default=0, max_length=255),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
