# Generated by Django 4.1.1 on 2022-09-15 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("battery_cells", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("csv_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvTimeSeriesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_time", models.CharField(default=0, max_length=255)),
                ("test_time_seconds", models.FloatField(default=0, max_length=255)),
                ("cycle_index", models.IntegerField(default=0)),
                ("current_a", models.FloatField(default=0, max_length=255)),
                ("voltage_v", models.FloatField(default=0, max_length=255)),
                ("charge_capacity_ah", models.FloatField(default=0, max_length=255)),
                ("discharge_capacity_ah", models.FloatField(default=0, max_length=255)),
                ("charge_energy_wh", models.FloatField(default=0, max_length=255)),
                ("discharge_energy_wh", models.FloatField(default=0, max_length=255)),
                (
                    "environment_temp_celsius",
                    models.FloatField(default=0, max_length=255),
                ),
                ("cell_temp_celsius", models.FloatField(default=0, max_length=255)),
                (
                    "battery_cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battery_cells.batterycell",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
